### ISSUE TITLE
Nice Modal integration with Material UI

### ISSUE THREAD

**Issue by RoyBikram** [eBay/nice-modal-react#101]
When we use Nice Modal with the Material UI library the theming of MUI is not passed down to the Dialog.
```
tsx
// use case
NiceModal.show(CustomDialog, {usedBeforeActivity: true});

// CustomDialog
const CustomDialog = () => {
  return <Dialog {/* config... */}>/* … */</Dialog>
}
```

**Comment by supnate** [comment]
```
// CustomDialog
const CustomDialog = (props) => {
  return <Dialog {...props} {/* config... */}>/* … */</Dialog>
}
```

**Comment by ruppysuppy** [comment]
@supnate sorry for the late reply, but Material UI components receive theme from context not props. Here is a sandbox to replicate the issue: https://codesandbox.io/s/mui-theme-not-working-with-nice-modal-j272g1?file=/demo.tsx:808-1029

**Comment by wallacer** [comment]
Running into this issue - is there a solution?
