### ISSUE TITLE
Globally check if any modal is visible

### ISSUE THREAD

**Issue by osrl** [eBay/nice-modal-react#115]
Is there nicer a way to check if a modal is open on the page globally? 
I'm currently using below method

```
const modals = useContext(NiceModal.NiceModalContext);
const isModalOpen = Object.keys(modals).length > 0
```

But this requires a new component inside the NiceModal.Provider.

**Comment by supnate** [comment]
This is the proper way. You can create a custom hook to do the check. Then just use the hook anywhere.
