### ISSUE TITLE
Unnecessary re-render when showing multiple modals..?

### ISSUE THREAD

**Issue by jackdunncode** [eBay/nice-modal-react#116]
I have this structure:

-- Parent
---- Modal
-------- Child Modal

When I call `NiceModal.show()` in the Parent, it opens the Modal, without re-rendering the Parent (which is desired!).
Then, in the Modal, I have a function to open a Child Modal. However this causes a re-render to the Modal (which is not desired!).

I have realised that `useModal` hook seems to be the culprit here, by watching the state change of `useModal`:
![image](https://github.com/eBay/nice-modal-react/assets/55561966/f7f4f0d6-8f25-4121-b7d8-ad69e02f7eff)

Here is the sequence of events, shown with `console.log`:

Opening Modal:
![image](https://github.com/eBay/nice-modal-react/assets/55561966/ba1be8ce-378e-437a-ae77-c2128c2cabe3)

Then opening Child Modal:
![image](https://github.com/eBay/nice-modal-react/assets/55561966/b987845d-a17f-49ce-9605-13f1e4cc5437)

As you can see, opening the Child Modal causes the first Modal to update (from `visible: false` back to `visible: true`).

How can I get around this?

**Comment by supnate** [comment]
Yes, it's a limitation for now, but a bit difficult to enhance: https://github.com/eBay/nice-modal-react/issues/58 . The workaround is use the static method `NiceModal.show(MyModal/id, args)` for your case.

**Comment by jackdunncode** [comment]
> Yes, it's a limitation for now, but a bit difficult to enhance: #58 . The workaround is use the static method `NiceModal.show(MyModal/id, args)` for your case.

I already am using the static method, in both Parent and Modal

**Comment by jackdunncode** [comment]
> > Yes, it's a limitation for now, but a bit difficult to enhance: #58 . The workaround is use the static method `NiceModal.show(MyModal/id, args)` for your case.
> 
> I already am using the static method, in both Parent and Modal

Simply destructuring the following was sufficient:

`const { visible, resolve, remove } = useModal();`

**Comment by supnate** [comment]
Should have been resolved in `v1.2.11`.
