### ISSUE TITLE
Hot module reloading / fast refresh support?

### ISSUE THREAD

**Issue by ewalti** [eBay/nice-modal-react#117]
I'm working on an older project that uses HMR. I find that if I have a modal open and I make an update to the code, everything else HMRs correctly, but the modal is stuck in time until I close it an re-open it. I tried using the declarative syntax as well to no avail. Is this just an issue with HMR? Would upgrading to fast refresh fix this? Does anyone else have this issue?

**Comment by fobos531** [comment]
Hello @ewalti , did you ever find a solution to this? I'm experiencing a similar issue, however what I'm experiencing is that the change in the modal refreshes the entire page.

**Comment by supnate** [comment]
@fobos531 can you show your usage? NiceModal shouldn't break HMR.

**Comment by baxxos** [comment]
@ewalti you closed this as "not planned" without any comment - could you please elaborate? 

I'm currently experiencing the same issue as you've described.

**Comment by dperetti** [comment]
HMR doesn't work for me either. My workaround is to create modals on the fly instead of exporting as pre-created.
```js
export const MyModal = <Modal>...</Modal>
```

```js
NiceModal.show(NiceModal.create(MyModal), {})
```
