### ISSUE TITLE
Disable body scroll lock and react portal

### ISSUE THREAD

**Issue by jakec-dev** [eBay/nice-modal-react#123]
Hi, this package works fantastically for modals however I can't figure out how to disable the body scroll lock and react portal usage so that I can use this for dialogs? i.e. be able to anchor the modal to another component while not having the modal blocking the user from interacting with the rest of the page while it's open. Think something like a notification dialog, or a tool tip.

Is this possible? I've looked at the docs and searched for past issues and it doesn't seem like this has been addressed anywhere.

**Comment by supnate** [comment]
Scroll lock is out of the scope of this lib, it's usually handled by the modals implementation.
