### ISSUE TITLE
Is this library able to be used with Next.js 13 and App router?

### ISSUE THREAD

**Issue by IvanZen** [eBay/nice-modal-react#126]
I'm attempting to use this library with Next.js 13 and App router, and running into the error:
`Error: No modal id found in NiceModal.useModal.`

**Comment by supnate** [comment]
How do you use it? Did you set the `ModalProvider` ?

**Comment by supnate** [comment]
where's `useModal` ?

**Comment by supnate** [comment]
np, good to know it works now!
