### ISSUE TITLE
Feature request: `NiceModal.activeModals`

### ISSUE THREAD

**Issue by orange4glace** [eBay/nice-modal-react#14]
First, thanks for the nice library.

It would be nice if there's a API to get current active modals like `NiceModal.activeModals` :>

**Comment by supnate** [comment]
Hi @orange4glace , could you please give any use cases for the feature?

**Comment by rlabarrett** [comment]
I have a need for something like this as well. The application I am working on has stacks of modals that once closed need to make some api calls. It would be preferable to make a single api call after all modals are closed versus a single calls as they close down.

**Comment by supnate** [comment]
This could be achieved by https://github.com/eBay/nice-modal-react/issues/63
