### ISSUE TITLE
How to bind props update via use NiceModal.show(MyModal, { loading, onOk })

### ISSUE THREAD

**Issue by FatDoge** [eBay/nice-modal-react#156]
I will send props.onOk, maybe async function, it will change loading status from false -> true -> false when user clicks button inside a modal. What I need is binding loading props and add loading style on clicked button, but I found it didn't work.

**Comment by FatDoge** [comment]
Or why not provide a optional object like
`NiceModal.show(MyModal, { loading, onOk }, { refreshDeps: [loading] })`

**Comment by supnate** [comment]
> Or why not provide a optional object like `NiceModal.show(MyModal, { loading, onOk }, { refreshDeps: [loading] })`

Data binding can only be used in hooks or components.

**Comment by Sminchdawg** [comment]
@FatDoge What are you using to get the values of "loading" and "onOk"? There is a good chance you could be reading those values directly in the modal instead of passing them through.

**Comment by FatDoge** [comment]
> @FatDoge What are you using to get the values of "loading" and "onOk"? There is a good chance you could be reading those values directly in the modal instead of passing them through.

Yes you are right, the existed code is weird and I rewrite the modal so I can control these inside it directly
