### ISSUE TITLE
Doesn't work well with NextJS

### ISSUE THREAD

**Issue by RobinLbt** [eBay/nice-modal-react#18]
I've tried to incorporate nice-modal-react on a NextJS project, but the provider doesn't work when wrapping the app at the root of the tree

```typescript
function MyApp({ Component, pageProps: { session, ...pageProps }}) {
  return (
    <NiceModal.Provider>
      <Component {...pageProps} />
    </NiceModal.Provider>
  )
}

export default MyApp
```

It works when wrapping a single page with the provider, so the problem comes from the provider itself.
Unfortunately, it's not a clean solution since I have to wrap every page with a Provider.

**Comment by tech-ea** [comment]
@RobinLbt I'm using NextJS and NiceMOdal, and I got it to work, but I am worried about performance. Are you still using NiceModal?Did you find a solution?
thanks Drew

**Comment by RobinLbt** [comment]
No I've switched to a custom implementation to have more controls over it

**Comment by dungle-scrubs** [comment]
> @RobinLbt I'm using NextJS and NiceMOdal, and I got it to work, but I am worried about performance. Are you still using NiceModal?Did you find a solution? thanks Drew

How were you able to get it to work with Nextjs? I have the same issue where it must be done at page-level and not within `_app.js`. Also, why are you worried about performance?  Thanks
