### ISSUE TITLE
MUI v5 onExited not supported

### ISSUE THREAD

**Issue by nuurcodes** [eBay/nice-modal-react#30]
I am using the muiDialog helper in MUI v5

e.g.
`<Dialog {...muiDialog(modal)}>...</Dialog>`

This issue with this is that the onExited property is not supported which means that `modal.remove()` is never called.

This is my workaround but it would be great if this handled in the library instead

`
    <Dialog
      {...muiDialog(modal)}
      TransitionProps={{
        onExited: () => {
          modal.resolveHide()
          modal.remove()
        }
      }}
    >
    `

**Comment by supnate** [comment]
Thanks @nuurcodes for reporting this!

**Comment by supnate** [comment]
Since `onExited` is under `TransitionProps` prop, we can't create a helper for nested props. It needs to be configured manually for Mui: https://ebay.github.io/nice-modal-react/#mui
