### ISSUE TITLE
Generic type error on `NiceModal.create`

### ISSUE THREAD

**Issue by SevenOutman** [eBay/nice-modal-react#46]
Hi, thanks for this great tool! I'm having little trouble with `NiceModal.create` method when it always require my component props to have an extra `[key: string]: unknown` property signature.

Here's my modal component with normal prop declaration but fail because of incompatibility with `Record<string, unknown>`.

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/8225666/160820590-233f96cc-ac0a-4d67-81df-fc397af2912d.png">

I always have to add this extra `[key: string]: unknown` property to dismiss the ts error.

<img width="680" alt="image" src="https://user-images.githubusercontent.com/8225666/160820771-35692529-07b4-4446-aef4-7464bab56bd7.png">

**Comment by john-pimq** [comment]
I have the same problem

**Comment by gnsharma-pepper** [comment]
Using type instead of interface will solve this. Maybe i can try to send a pr to fix this at the typescript level.

**Comment by supnate** [comment]
Thanks @gnsharma-pepper , PR is welcome!

**Comment by gnsharma** [comment]
@supnate created a pr for this.

**Comment by supnate** [comment]
Thanks @gnsharma for the fix and providing the context why it happens. Published by `v1.2.5` .
