### ISSUE TITLE
Support for React Native?

### ISSUE THREAD

**Issue by Andres6936** [eBay/nice-modal-react#74]
It is possible to use this library with React Native?

**Comment by supnate** [comment]
I thinks so, though not tried. This lib doesn't have any UI implementation but only state management.

**Comment by BrianCodeItUp** [comment]
@Andres6936  You can use it with React Native. I tired it with react-native-modal. Work like a charm.

**Comment by Andres6936** [comment]
Thanks, yes work with UI Kitten in React Native.
