### ISSUE TITLE
Radix support

### ISSUE THREAD

**Issue by jetaix** [eBay/nice-modal-react#84]
Do you plan to support [Radix](https://www.radix-ui.com/docs/primitives/components/dialog) ?
or a way to achieve this with a clear example like bootstrap, antd ... ?

**Comment by supnate** [comment]
Hi @jetaix ,  nice modal could be used with any ui library. If you mean a helper, then you can create a helper yourself since it's just several lines of code. For example: https://github.com/eBay/nice-modal-react/blob/a1b9f82c260b5750dd7057fa2709672c873a10d3/src/index.tsx#L550 .
