### ISSUE TITLE
Add type safety to modal.show()

### ISSUE THREAD

**Issue by avivm** [eBay/nice-modal-react#9]
First of all thanks for a great library!

I think it will be great if you can add type safety to the modal arguments when calling the show method. Could be using generics:

`modal.show<Props>(props: Props)`

Of course it will be amazing if somehow it will infer it from the modal component itself but I'm not sure it's possible and the generics solution at least gives basic type safety.

Thanks!

**Comment by supnate** [comment]
Thanks! This looks like a great suggestion. However because it support using id to create a modal so I'm afraid it is impossible to infer the props type since it's runtime behavior.

However, if use a component for the `useModal(MyDialog)` hook maybe it can be type safe. I will take a look.

**Comment by LoicUV** [comment]
Did you have the time to look into this by any chance ?

**Comment by xxleyi** [comment]
https://github.com/eBay/nice-modal-react/pull/20

Make a pull request, try to give better TS type.

**Comment by supnate** [comment]
Thanks @xxleyi for the contribution! It's already published in the version `v1.2.0`.

**Comment by lukasz-karolewski** [comment]
I'm having trouble understanding how it helps to specify type of the modal... From usage perspective what I'd expect that you strongly type modal props and return strongly typed promise

but this changes does not accomplish that I still get Record<string, unknown> and Promise
and I'm not sure how, as a library user, i benefit in any way from typing a modal...

Maybe you can you examples of usage guys had in mind?

**Comment by xxleyi** [comment]
@lukasz-karolewski The improvement is, when you use React component with useModal, show, the props will be `Partial<Props of React component> | undefined`.

You can give it a try in here: https://codesandbox.io/s/nice-modal-react-ts-type-0gql5?file=/src/ModalTypeExample.tsx

**Comment by laukaichung** [comment]
> @lukasz-karolewski The improvement is, when you use React component with useModal or show, the props will be `Partial<Props of React component> | undefined`.
> 
> You can give it a try in here: https://codesandbox.io/s/nice-modal-react-ts-type-0gql5?file=/src/ModalTypeExample.tsx

How can I fix 
````
No overload matches this call.
  Overload 1 of 2, '(modal: ({ a, b }: { a: number; b: string; }) => Element, args?: Partial<Omit<{ a: number; b: string; }, "id">> | undefined): Promise<unknown>', gave the following error.
    Type 'string' is not assignable to type 'number | undefined'.
  Overload 2 of 2, '(modal: string, args?: Record<string, unknown> | undefined): Promise<unknown>', gave the following error.
    Argument of type '({ a, b }: { a: number; b: string; }) => Element' is not assignable to parameter of type 'string'.ts(2769)
````

as shown in the codesandbox example?

**Comment by xxleyi** [comment]
> > @lukasz-karolewski The improvement is, when you use React component with useModal or show, the props will be `Partial<Props of React component> | undefined`.
> > You can give it a try in here: https://codesandbox.io/s/nice-modal-react-ts-type-0gql5?file=/src/ModalTypeExample.tsx
> 
> How can I fix
> 
> ```
> No overload matches this call.
>   Overload 1 of 2, '(modal: ({ a, b }: { a: number; b: string; }) => Element, args?: Partial<Omit<{ a: number; b: string; }, "id">> | undefined): Promise<unknown>', gave the following error.
>     Type 'string' is not assignable to type 'number | undefined'.
>   Overload 2 of 2, '(modal: string, args?: Record<string, unknown> | undefined): Promise<unknown>', gave the following error.
>     Argument of type '({ a, b }: { a: number; b: string; }) => Element' is not assignable to parameter of type 'string'.ts(2769)
> ```
> 
> as shown in the codesandbox example?

As the message say: Type 'string' is not assignable to type 'number | undefined', where number part is right.
