### ISSUE TITLE
[Question] Typesafe args

### ISSUE THREAD

**Issue by osrl** [eBay/nice-modal-react#95]
I'm not an expert ts developer so there might be something I missed. When I change the signature of the `show` method to below, args parameter becomes type safe, instead of any. Is there a reason why this isn't the case?

`export declare function show<T extends any, Arg extends any>(modal: React.FC<Arg>, args?: NiceModalArgs<React.FC<Arg>>): Promise<T>;`

**Comment by Yedidyar** [comment]
I also have an issue when I use the show or create functions with `plugin:@typescript-eslint/recommended-requiring-type-checking`  rules.
 I get:

- Unsafe assignment of an `any` value
- Unsafe member access .create on an `any` value.
- Unsafe call of an `any` typed value.
- Unsafe return of an `any` typed value.
